### PR TITLE
Documentation for list/load projects and asset creation.

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
Looks good!

**Comment by mottosso** [comment]
A few notes, now that I've actually seen the site:

1. `avalon --ls` isn't part of /docker yet?
2. Can skip the HTML markup for tabs if the code is identical cross-platform, like the plain `avalon --ls` commands. Regular GitHub style fenced code blocks works too.
3. Should include example output where possible, like for `--ls`. I find it provides better familiarity and builds trust with a command quicker than having them execute it on their own. And, if things to wrong, they'll know because the output isn't what they know it should be.

**Comment by mottosso** [comment]
I made a few edits; primarily to the order in which information is presented.

I figure these guides are written to be followed like a book, rather than as a reference, and after having created two projects I figure you'd not need `--ls` since you know what you've got.

Instead, I put asset creation into the project you already know, and put `--ls` in a "hint" bubble.

We *should* still have a chapter for `--ls` I think, for when you do need to know what projects are available. However most of the time, the projects available in the database is reflected on disk and it's expected you know where your projects are and could view them from a file browser. For example, by looking at `c:\projects\`

`--ls` is probably better suited for when you *don't* already have the projects on disk. Perhaps it would make better sense to introduce `--ls` right after having imported the example Batman project?

**Comment by tokejepsen** [comment]
> avalon --ls isn't part of /docker yet?

No, not yet. Was waiting on https://github.com/getavalon/core/pull/318 to be merged.

> --ls is probably better suited for when you don't already have the projects on disk. Perhaps it would make better sense to introduce --ls right after having imported the example Batman project?

Yeah, I found it tricky to figure out where to place this. My thoughts were that you may know what you have on disk, but since you are unfamiliar with Avalon you dont know what is in the database yet. So its like a confirmation about what you have done so far it working, and you are on the right track. Especially if we include an example output.

**Pull request merged**
